### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by breezytm** [PierrickGT/pokt-koinly-accounting#1]
Hey Pierrick, 

When I run the project, it completed successfully but the ``.csv`` file only contains the header but no actual data. Can you please take a look to see if the project needs updating to reflect the recent poktscan changes. 

```
$ yarn start
yarn run v1.22.19
$ ts-node request.ts
Done in 4.71s.
```

**Comment by PierrickGT** [comment]
> Hey Pierrick,
> 
> When I run the project, it completed successfully but the `.csv` file only contains the header but no actual data. Can you please take a look to see if the project needs updating to reflect the recent poktscan changes.
> 
> ```
> $ yarn start
> yarn run v1.22.19
> $ ts-node request.ts
> Done in 4.71s.
> ```

Hi,
I've tested and it's still running properly on my end.
Have you setup and loaded your `.envrc` and adjusted the date range?
https://github.com/PierrickGT/pokt-koinly-accounting#usage

**Comment by breezytm** [comment]
I believe so

1. cp .envrc.example .envrc
2. edit .envrc file 
3. add poktscan api key
4. add node address
5. direnv allow
6. yarn start

**Comment by PierrickGT** [comment]
> I believe so
> 
> 1. cp .envrc.example .envrc
> 2. edit .envrc file
> 3. add poktscan api key
> 4. add node address
> 5. direnv allow
> 6. yarn start

And you've setup direnv?
https://direnv.net

Does it return your API key if in the terminal you type: `echo $POKTSCAN_API_KEY` ?

**Comment by breezytm** [comment]
```
direnv allow .
direnv: loading ~/pokt-koinly-accounting/.envrc
direnv: export +NODE_ADDRESS +POKTSCAN_API_KEY
```

``echo $POKTSCAN_API_KEY`` and ``echo $NODE_ADDRESS`` returns the API key and POKT node address

**Comment by breezytm** [comment]
Do you mind reaching out in discord Breezytm#9710

**Comment by PierrickGT** [comment]
> Do you mind reaching out in discord Breezytm#9710

Can you add me as a friend please? Pierrick#1350
It looks like you are not accepting friend requests.
